# 配置数据源
spring:
  application:
    name: xunwu-project
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://118.24.38.184:3306/xunwu?autoReconnect=true
    username: root
    password: sean

# 配置日志
logging:
  level:
    root: warn
    com.sean.dao: debug
  pattern:
    console: '%p%m%n'